#pragma once

enum class ScreenState {
	UNKNOWN,
	ENTERING_RANK_SHOWN,
	RANK_SHOWN,
	ENTERING_SELECT_POKEMON,
	SELECT_POKEMON,
	LEAVING_SELECT_POKEMON,
	ENTERING_CONFIRM_POKEMON,
	CONFIRM_POKEMON,
	ENTERING_MATCH,
	MATCH,
	ENTERING_RESULT,
	RESULT,
};
